import type { Transaction } from './types'

export const transactions: Transaction[] = [
  {
    id: '1',
    date: '2026-03-24',
    description: 'The Greenhouse Bistro',
    merchant: 'POS-89210',
    category: 'Food & Dining',
    type: 'Expense',
    amount: -142.5,
  },
  {
    id: '2',
    date: '2026-03-23',
    description: 'Uber Technologies',
    merchant: 'City Transit NY',
    category: 'Transport',
    type: 'Expense',
    amount: -38.2,
  },
  {
    id: '3',
    date: '2026-03-20',
    description: 'Global Systems Corp',
    merchant: 'Salary Deposit',
    category: 'Salary',
    type: 'Income',
    amount: 8500.0,
  },
  {
    id: '4',
    date: '2026-03-18',
    description: 'Nordic Design Store',
    merchant: 'Home Goods & Decor',
    category: 'Shopping',
    type: 'Expense',
    amount: -245.99,
  },
  {
    id: '5',
    date: '2026-03-16',
    description: 'City Power & Light',
    merchant: 'Monthly Utilities',
    category: 'Utilities',
    type: 'Expense',
    amount: -189.0,
  },
  {
    id: '6',
    date: '2026-03-14',
    description: 'StreamVault Premium',
    merchant: 'Subscription Service',
    category: 'Entertainment',
    type: 'Expense',
    amount: -15.99,
  },
  {
    id: '7',
    date: '2026-03-12',
    description: 'Wellness Clinic',
    merchant: 'Health Checkup',
    category: 'Healthcare',
    type: 'Expense',
    amount: -320.0,
  },
  {
    id: '8',
    date: '2026-03-10',
    description: 'Freelance Project',
    merchant: 'Web Development',
    category: 'Freelance',
    type: 'Income',
    amount: 2400.0,
  },
  {
    id: '9',
    date: '2026-03-08',
    description: 'Fresh Mart Grocery',
    merchant: 'Weekly Groceries',
    category: 'Food & Dining',
    type: 'Expense',
    amount: -96.45,
  },
  {
    id: '10',
    date: '2026-03-05',
    description: 'Metro Rail Pass',
    merchant: 'Monthly Commute',
    category: 'Transport',
    type: 'Expense',
    amount: -120.0,
  },
  {
    id: '11',
    date: '2026-03-05',
    description: 'Metro Rail Pass',
    merchant: 'Monthly Commute',
    category: 'Transport',
    type: 'Expense',
    amount: -120.0,
  }
]

export const categoryIcons: Record<string, string> = {
  'Food & Dining': '🍽️',
  Transport: '🚗',
  Salary: '💰',
  Shopping: '🛍️',
  Utilities: '⚡',
  Entertainment: '🎬',
  Healthcare: '🏥',
  Freelance: '💻',
}
